require "user.options"
require "user.plugins"
-- require "user.alpha"
require "user.colorscheme"
require "user.keymaps"
require "user.treesitter"
require "user.telescope"
require "user.lualine"
require "user.bufferline"
require "user.toggleterm"
require "user.alpha"
